name: Validar los pull request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pull_request_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Realizar análisis de SAST
        run: echo "Realizando análisis de SAST"

      - name: Comprobar requisitos
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "allow_pull=true" >> $GITHUB_ENV
          else
            echo "allow_pull=false" >> $GITHUB_ENV
          fi

      - name: Permitir Pull Request
        if: ${{ env.allow_pull == 'true' }}
        run: echo "Permitiendo Pull Request"

      - name: Impedir Pull Request
        if: ${{ env.allow_pull == 'false' }}
        run: |
          echo "Build fallida. Impidiendo Pull Request"
          exit 1

      - name: Guardar archivo como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-allow-pull-request
          path: allow_pull_request.txt
